# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13A-ZOuS-e_bohmeMXKYbiQYXtYVJ12Eb
"""

import pandas as pd
import numpy as np

data = pd.read_csv('/content/Telco_Churn_Dataset.csv')

data.dtypes

data.head(10000)

data.tail()

